# Generated by Django 6.0.2 on 2026-06-09 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_transaction_transaction_type_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('ORDER', 'Order Payment'), ('TOPUP', 'Wallet Top-up'), ('CLUB', 'Club Subscription')], default='ORDER', max_length=10),
        ),
    ]
