# Generated by Django 6.0.2 on 2026-02-18 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_coach',
            field=models.BooleanField(default=False, help_text='Set to True when a teacher is promoted to a coach/tutor.'),
        ),
    ]
