# Generated by Django 6.0.2 on 2026-02-19 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educoach', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachingsession',
            name='meeting_link',
            field=models.CharField(blank=True, null=True),
        ),
    ]
