# Generated by Django 6.0.2 on 2026-02-21 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educoach', '0002_alter_coachingsession_meeting_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachAvailabilityRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.AlterModelOptions(
            name='coachingsession',
            options={'ordering': ['-date', '-start_time']},
        ),
        migrations.RenameField(
            model_name='coachingsession',
            old_name='time',
            new_name='start_time',
        ),
        migrations.AddField(
            model_name='coachingsession',
            name='booking_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='coachingsession',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coachingsession',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='educoach.coach'),
        ),
        migrations.AlterField(
            model_name='coachingsession',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booked_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='coachingsession',
            index=models.Index(fields=['coach', 'date', 'status'], name='educoach_co_coach_i_69f0b4_idx'),
        ),
        migrations.AddField(
            model_name='coachavailabilityrange',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_ranges', to='educoach.coach'),
        ),
        migrations.AddIndex(
            model_name='coachavailabilityrange',
            index=models.Index(fields=['coach', 'day_of_week'], name='educoach_co_coach_i_3d9dfb_idx'),
        ),
    ]
