# Generated by Django 6.0.2 on 2026-02-21 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educoach', '0003_coachavailabilityrange_alter_coachingsession_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachEarnings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_type', models.CharField(choices=[('EARNING', 'Earning'), ('WITHDRAWAL', 'Withdrawal')], max_length=20)),
                ('status', models.CharField(choices=[('EXPECTED', 'Expected'), ('EARNED', 'Earned'), ('WITHDRAWN', 'Withdrawn'), ('CANCELLED', 'Cancelled')], default='EXPECTED', max_length=20)),
                ('duration', models.PositiveIntegerField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('transaction_id', models.CharField(help_text='Session Booking ID or Withdrawal ID', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger', to='educoach.coach')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='earnings_records', to='educoach.coachingsession')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Coach Earnings',
                'ordering': ['-created_at'],
            },
        ),
    ]
