# Generated by Django 6.0.2 on 2026-02-23 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educoach', '0004_coachearnings'),
        ('payments', '0003_withdrawal'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachingsession',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='coachingsession',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coaching_sessions', to='payments.transaction'),
        ),
    ]
