# Generated by Django 6.0.2 on 2026-03-01 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educoach', '0005_coachingsession_payment_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HMSSession',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('room_id', models.CharField(max_length=100)),
                ('customer_id', models.CharField(max_length=100)),
                ('app_id', models.CharField(max_length=100)),
                ('user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HMSPeer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peer_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=100)),
                ('user_id', models.CharField(max_length=255)),
                ('joined_at', models.DateTimeField()),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peers', to='educoach.hmssession')),
            ],
            options={
                'unique_together': {('session', 'peer_id')},
            },
        ),
    ]
