# Generated by Django 6.0.2 on 2026-03-02 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educoach', '0006_hmssession_hmspeer'),
    ]

    operations = [
        migrations.AddField(
            model_name='hmssession',
            name='internal_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hms_sessions', to='educoach.coachingsession'),
        ),
    ]
