# Generated by Django 6.0.2 on 2026-03-02 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educoach', '0007_hmssession_internal_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hmssession',
            name='app_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hmssession',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hmssession',
            name='customer_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hmssession',
            name='room_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hmssession',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
