# Generated by Django 6.0.2 on 2026-02-22 16:59

import django.db.models.deletion
import eduquest.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduquest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialorder',
            name='address',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='materialorder',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='materialorder',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='materialorder',
            name='estimated_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='materialorder',
            name='levels_data',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='materialorder',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='materialorder',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='materialorder',
            name='reference',
            field=models.CharField(default=eduquest.models.generate_quest_reference, max_length=20),
        ),
        migrations.AddField(
            model_name='materialorder',
            name='representative',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='materialorder',
            name='school_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='materialorder',
            name='session',
            field=models.CharField(blank=True, choices=[('BOT', 'Beginning of Term'), ('MID', 'Mid Term'), ('EOT', 'End of Term')], max_length=10),
        ),
        migrations.AddField(
            model_name='materialorder',
            name='total_sets',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='materialorder',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='eduquest.material'),
        ),
    ]
