# Generated by Django 6.0.2 on 2026-02-22 17:00

import eduquest.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduquest', '0002_materialorder_address_materialorder_delivery_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialorder',
            name='reference',
            field=models.CharField(default=eduquest.models.generate_quest_reference, max_length=20, unique=True),
        ),
    ]
