# Generated by Django 6.0.2 on 2026-02-22 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduquest', '0004_materialorder_transaction_alter_materialorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialorder',
            name='expected_delivery_date',
            field=models.DateField(blank=True, help_text='Date the administration manages to deliver by', null=True),
        ),
        migrations.AlterField(
            model_name='materialorder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DECLINED', 'Declined'), ('PAID', 'Paid'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
