# Generated by Django 6.0.2 on 2026-02-17 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edushop', '0003_order_transaction_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Unpaid', 'Unpaid'), ('Paid', 'Paid'), ('Processing', 'Processing'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
