"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv

# Load .env before other imports or config calls
load_dotenv()

from decouple import config
GMAIL_TOKEN_JSON = config("GMAIL_TOKEN_JSON", default="")
GOOGLE_OAUTH2_CLIENT_ID = config("GOOGLE_OAUTH2_CLIENT_ID", default="")
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-+xbvwu-&q+5a_3p#1%xu3)rx_2&glkt$2b%vmbog$nlb8f01+*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


CORS_ALLOW_ALL_ORIGINS = True

CSRF_TRUSTED_ORIGINS = [

    'https://edumerc.up.railway.app',
    'http://localhost:5174',

      ]

# CORS_ALLOWED_ORIGINS = [
#     'http://localhost:5174',
#     'https://edumerc.up.railway.app',

# ]







# Application definition

INSTALLED_APPS = [
    "corsheaders",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_filters',
    'storages',
    'rest_framework',
    'rest_framework_simplejwt',
    'users',
    'edushop',
    'edufundme',
    'core',
    'eduquest',
    'edupedia',
    'payments',
    'educoach',
    'notifications',
    'educlubs',
]

MIDDLEWARE = [

    "corsheaders.middleware.CorsMiddleware",   # must be high up


    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }





DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME', default='railway'),
        'USER': config('DB_USER', default='postgres'),
        'PASSWORD': config('DB_PASSWORD', default='Shsd.vWzAj8c8Yg5vlqXLpIIEassK_Zi'),
        'HOST': config('DB_HOST', default='gondola.proxy.rlwy.net'),
        'PORT': config('DB_PORT', default='30149'),
        
        # Connection management and performance
        'CONN_MAX_AGE': config('CONN_MAX_AGE', default=600, cast=int),
        'CONN_HEALTH_CHECKS': True,
        
        'OPTIONS': {
            'connect_timeout': 5,
            # Railway internal connections might not need SSL, 
            # but external tunnels often benefit from 'require' or 'prefer'
            'sslmode': config('DB_SSLMODE', default='prefer'),
        },
    }
}








# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'users.User'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=600),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=2),
}


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "static"

# ---------------------------------------------------------------------------
# Google Cloud Storage – Media files  (Django 4.2+ STORAGES API)
# ---------------------------------------------------------------------------
GCS_BUCKET_NAME = config('GCS_BUCKET_NAME', default='')
GCS_CREDENTIALS_FILE = config('GCS_CREDENTIALS_FILE', default='')  # path to service-account JSON

if GCS_BUCKET_NAME:
    GS_BUCKET_NAME = GCS_BUCKET_NAME
    GS_DEFAULT_ACL = None        # public access handled via bucket IAM (allUsers → Object Viewer)
    GS_QUERYSTRING_AUTH = False  # serve clean permanent URLs (no signed tokens)
    if GCS_CREDENTIALS_FILE:
        from google.oauth2 import service_account
        GS_CREDENTIALS = service_account.Credentials.from_service_account_file(
            GCS_CREDENTIALS_FILE
        )
    MEDIA_URL = f'https://storage.googleapis.com/{GCS_BUCKET_NAME}/media/'
    GS_LOCATION = 'media'  # stores all uploaded files under the media/ prefix in the bucket
    # Django 4.2+ requires STORAGES dict — DEFAULT_FILE_STORAGE no longer works
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.gcloud.GoogleCloudStorage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }
else:
    # Fallback: local storage during development when bucket is not configured
    MEDIA_URL = '/media/'
    MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# PesaPal V3 Production Settings

PESAPAL_CONSUMER_KEY = "7wmnV5XyjVMs3OHMPuiu1xpwtDCC4IVi"
PESAPAL_CONSUMER_SECRET = "16T/O+dQAAGiTWhkaOTlfsH1r0w="
PESAPAL_IPN_ID = "b8dab8c6-23a6-4989-9602-dab89a2bc831"


# The URL where PesaPal will redirect the user after payment
PESAPAL_CALLBACK_URL = 'https://1cf2-41-84-202-116.ngrok-free.app/api/v1/payments/initiate/payment-success' 



# load_dotenv() is now at the top
