# Generated by Django 6.0.2 on 2026-02-15 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Social', 'Social'), ('Teacher', 'Teacher'), ('Subject', 'Subject')], max_length=50)),
                ('level', models.CharField(blank=True, choices=[('Nursery', 'Nursery'), ('P1', 'Primary 1'), ('P2', 'Primary 2'), ('P3', 'Primary 3'), ('P4', 'Primary 4'), ('P5', 'Primary 5'), ('P6', 'Primary 6'), ('P7', 'Primary 7'), ('S1', 'Secondary 1'), ('S2', 'Secondary 2'), ('S3', 'Secondary 3'), ('S4', 'Secondary 4'), ('S5', 'Secondary 5'), ('S6', 'Secondary 6'), ('General', 'General (All Levels)')], default='General', max_length=50, null=True)),
                ('description', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='club_covers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AskAIQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='Anonymous', max_length=255)),
                ('query', models.TextField()),
                ('response', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_queries', to='educlubs.club')),
            ],
        ),
        migrations.CreateModel(
            name='ClubDiscussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='Anonymous', max_length=255)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='educlubs.club')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PracticalApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('guide', models.TextField(help_text='Step-by-step guide or explanation')),
                ('image', models.ImageField(blank=True, null=True, upload_to='practical_apps/')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practical_apps', to='educlubs.club')),
            ],
        ),
        migrations.CreateModel(
            name='RoleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('bio', models.TextField()),
                ('contribution', models.TextField(help_text='Their contribution to this field')),
                ('image', models.ImageField(blank=True, null=True, upload_to='role_models/')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_models', to='educlubs.club')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='educlubs.club')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content_type', models.CharField(choices=[('Text', 'Text Content'), ('Video', 'Video URL'), ('File', 'File Download')], default='Text', max_length=20)),
                ('text_content', models.TextField(blank=True, null=True)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('file_content', models.FileField(blank=True, null=True, upload_to='lesson_files/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='educlubs.topic')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
