# Generated by Django 6.0.2 on 2026-03-03 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educlubs', '0001_initial'),
    ]

    def create_default_sections(apps, schema_editor):
        Section = apps.get_model('educlubs', 'Section')
        Section.objects.get_or_create(name='Primary', defaults={'description': 'Primary Education Section'})
        Section.objects.get_or_create(name='Secondary', defaults={'description': 'Secondary Education Section'})

    def remove_default_sections(apps, schema_editor):
        Section = apps.get_model('educlubs', 'Section')
        Section.objects.filter(name__in=['Primary', 'Secondary']).delete()

    operations = [
        migrations.RunPython(create_default_sections, remove_default_sections),
    ]
