# Generated by Django 6.0.2 on 2026-02-16 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educlubs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubdiscussion',
            name='club',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='club',
        ),
        migrations.AddField(
            model_name='askaiquery',
            name='social_club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_queries', to='educlubs.socialclub'),
        ),
        migrations.AddField(
            model_name='askaiquery',
            name='teacher_club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_queries', to='educlubs.teacherclub'),
        ),
        migrations.AddField(
            model_name='clubdiscussion',
            name='social_club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='educlubs.socialclub'),
        ),
        migrations.AddField(
            model_name='clubdiscussion',
            name='subject_club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='educlubs.subjectclub'),
        ),
        migrations.AddField(
            model_name='clubdiscussion',
            name='teacher_club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='educlubs.teacherclub'),
        ),
        migrations.AddField(
            model_name='practicalapplication',
            name='social_club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='practical_apps', to='educlubs.socialclub'),
        ),
        migrations.AddField(
            model_name='practicalapplication',
            name='teacher_club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='practical_apps', to='educlubs.teacherclub'),
        ),
        migrations.AddField(
            model_name='rolemodel',
            name='social_club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_models', to='educlubs.socialclub'),
        ),
        migrations.AddField(
            model_name='rolemodel',
            name='teacher_club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_models', to='educlubs.teacherclub'),
        ),
        migrations.AddField(
            model_name='socialclub',
            name='icon',
            field=models.CharField(default='🤝', max_length=50),
        ),
        migrations.AddField(
            model_name='subjectclub',
            name='icon',
            field=models.CharField(default='📚', max_length=50),
        ),
        migrations.AddField(
            model_name='teacherclub',
            name='icon',
            field=models.CharField(default='👨\u200d🏫', max_length=50),
        ),
        migrations.AddField(
            model_name='topic',
            name='social_club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='educlubs.socialclub'),
        ),
        migrations.AddField(
            model_name='topic',
            name='subject_club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='educlubs.subjectclub'),
        ),
        migrations.AddField(
            model_name='topic',
            name='teacher_club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='educlubs.teacherclub'),
        ),
    ]
