# Generated by Django 6.0.2 on 2026-03-03 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educlubs', '0002_seed_sections'),
    ]

    def create_levels(apps, schema_editor):
        Section = apps.get_model('educlubs', 'Section')
        Level = apps.get_model('educlubs', 'Level')

        try:
            primary = Section.objects.get(name='Primary')
            secondary = Section.objects.get(name='Secondary')
        except Section.DoesNotExist:
            print("Required sections (Primary/Secondary) do not exist. Skipping Level seeding.")
            return

        # Seed P.1 - P.7
        for i in range(1, 8):
            Level.objects.get_or_create(
                name=f'P.{i}',
                section=primary,
                defaults={'order': i}
            )

        # Seed S.1 - S.4
        for i in range(1, 5):
            Level.objects.get_or_create(
                name=f'S.{i}',
                section=secondary,
                defaults={'order': i + 10} # S.1 starts after P.x
            )

    def remove_levels(apps, schema_editor):
        Level = apps.get_model('educlubs', 'Level')
        Level.objects.all().delete()

    operations = [
        migrations.RunPython(create_levels, remove_levels),
    ]
