# Generated by Django 6.0.2 on 2026-06-08 09:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educlubs', '0003_seed_levels'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('icon', models.CharField(help_text='Icon name or emoji', max_length=64)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('subject', 'Subject Club'), ('social', 'Social Club'), ('teacher', 'Teacher Club')], default='subject', max_length=10)),
                ('popular', models.BooleanField(default=False, help_text='Show popular badge')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clubs', to='educlubs.level')),
            ],
            options={
                'verbose_name': 'Club',
                'verbose_name_plural': 'Clubs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DiscussionMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('comment', models.TextField()),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussion', to='educlubs.club')),
            ],
            options={
                'verbose_name': 'Discussion Message',
                'verbose_name_plural': 'Discussion Messages',
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=255)),
                ('content', models.TextField(help_text='Markdown content for the note')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='educlubs.club')),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PracticalProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('steps', models.JSONField(help_text='Ordered list of step strings')),
                ('club', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='practical', to='educlubs.club')),
            ],
            options={
                'verbose_name': 'Practical Project',
                'verbose_name_plural': 'Practical Projects',
            },
        ),
        migrations.CreateModel(
            name='RoleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contribution', models.TextField()),
                ('image', models.URLField(blank=True, null=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_models', to='educlubs.club')),
            ],
            options={
                'verbose_name': 'Role Model',
                'verbose_name_plural': 'Role Models',
                'ordering': ['name'],
            },
        ),
    ]
