# Generated by Django 6.0.2 on 2026-02-24 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edupedia', '0002_schoolreview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='cover_image',
            new_name='coverImage',
        ),
    ]
